### ISSUE TITLE
no signal.SIGPIPE on windows

### ISSUE THREAD

**Issue by breisfeld** [sdg-mit/gitless#116]
Platform: Windows 7

```
$ python
Python 3.5.1 |Anaconda custom (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

$ git rev-parse HEAD
9e31a4624c0884c7169733adafa22aca87ffc6af
```

```
$ gl history
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:

  0.8.4

  Traceback (most recent call last):
    File "D:\Python\Anaconda\lib\site-packages\gitless-0.8.4-py3.5.egg\gitless\cli\gl.py", line 82, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "D:\Python\Anaconda\lib\site-packages\gitless-0.8.4-py3.5.egg\gitless\cli\gl_history.py", line 50, in main
      helpers.page(tf.name, repo)
    File "D:\Python\Anaconda\lib\site-packages\gitless-0.8.4-py3.5.egg\gitless\cli\helpers.py", line 74, in page
      from signal import signal, SIGPIPE, SIG_DFL
  ImportError: cannot import name 'SIGPIPE'
```

**Comment by spderosso** [comment]
oops, sorry about that. 38457cc357e5d86f4232b12230fe5228cfd7cd35 introduced the bug (I wish travis ci had an option to run tests on Windows).

**Comment by breisfeld** [comment]
I don't know if there would be unintended side effects, but it might be okay to just introduce a platform-specific 'fix': 

```
if sys.platform != 'win32':
  from signal import signal, SIGPIPE, SIG_DFL
  signal(SIGPIPE, SIG_DFL)
```

**Comment by spderosso** [comment]
Yes, that would prevent the exception from happening. But I have to test if we need to do something in Windows to prevent the "broken pipe error" that occurs in Unix if we don't have that code. I'll look into it later tonight. In the meantime, since it seems you are installing Gitless from the repo, you can change the head to commit d0aabff3cd0c7cf466d4fe67d11c3a1a156d57a9 and reinstall.

**Comment by spderosso** [comment]
d948e16a97a1aff2efdd09a92bb998e4e1041079
