### ISSUE TITLE
gl init fails asking for credentials

### ISSUE THREAD

**Issue by techtonik** [sdg-mit/gitless#145]
`gl init` finishes badly with screen painted in bloody color.
```
>gl init

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

**Comment by techtonik** [comment]
`tox` tests in #146 also fail because of it:
```
======================================================================
ERROR: test_create_existing (gitless.tests.test_core.TestRemoteCreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\gitless\gitless\tests\test_core.py", line 884, in setUp
    remote_repo = core.init_repository()
  File "C:\gitless\gitless\core.py", line 73, in init_repository
    git.commit(allow_empty=True, m='Initialize repository')
  File "c:\gitless\tox~1\py27\lib\site-packages\pbs.py", line 456, in __call__
    return RunningCommand(command_ran, process, call_args, actual_stdin)
  File "c:\gitless\tox~1\py27\lib\site-packages\pbs.py", line 168, in __init__
    self._handle_exit_code(self.process.wait())
  File "c:\gitless\tox~1\py27\lib\site-packages\pbs.py", line 235, in _handle_exit_code
    raise get_rc_exc(rc)(self.command_ran, self._stdout, self._stderr)
ErrorReturnCode_128: 

Ran: u'git --no-pager commit -m Initialize repository --allow-empty'

STDOUT:

  

STDERR:

  
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the ... (110 more, please see e.stderr)
-------------------- >> begin captured logging << --------------------
root: DEBUG: Created temporary directory c:\users\user\appdata\local\temp2\gl-core-testdvaetw
--------------------- >> end captured logging << ---------------------
```
