### ISSUE TITLE
gl crashes if directory does not contain a repo with AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by bK4gYuRo** [sdg-mit/gitless#179]
If I run gl command in a directory which does not contain a git repository, it crashes:

ks-mbp:foo ks$ ls -la
total 0
drwxr-xr-x    2 ks  staff    64 Aug  7 12:01 .
drwxr-xr-x  219 ks  staff  7008 Aug  7 12:30 ..
ks-mbp:foo ks$ gl -h
Traceback (most recent call last):
  File "/opt/local/bin/gl", line 11, in <module>
    load_entry_point('gitless==0.8.6', 'console_scripts', 'gl')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gitless/cli/gl.py", line 43, in <module>
    repo = core.Repository()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gitless/core.py", line 115, in __init__
    self.git_repo = pygit2.Repository(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygit2/repository.py", line 1208, in __init__
    path = path.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

I cannot even create a repository with "gl init" as it crashes with the same error.

**Comment by bK4gYuRo** [comment]
Apparently this behavior was caused by recent upgrade of libgit2 and py27-pygit2 form 0.26.4_0 to 0.27.4. Rolling back to 0.26.4_0 restored normality. Is there any incompatibility between gitless and libgit2 0.27.4?

**Comment by spderosso** [comment]
Thanks for looking into this. A breaking change was introduced in pygit 0.27 ([changelog link](https://github.com/libgit2/pygit2/blob/master/CHANGELOG.rst#0271-2018-06-02)) but PR #180 fixed it. If you are running Gitless 0.8.6 then you should use pygit 0.26, if are running from HEAD then both pygit 0.26 and pygit 0.27 should work.

**Comment by spderosso** [comment]
The breaking change introduced in pygit2 0.27 is also causing it to crash on `gl init`. I will cut a new release with the fix soon.
