### ISSUE TITLE
gl fails with pycparser>2.18

### ISSUE THREAD

**Issue by sirlucjan** [sdg-mit/gitless#206]
gitless fails with pycparser 2.19.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pycparser 2.19 (/usr/lib/python3.7/site-packages), Requirement.parse('pycparser<2.18'), {'pygit2'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycparser<2.18' distribution was not found and is required by pygit2
```
I've downgarded pycparser to 2.17 and error doesn't occur. 

```
$ pacman -Ss pycparser
extra/python-pycparser 2.19-1 [installed]
    C parser and AST generator written in Python
extra/python2-pycparser 2.19-1
    C parser and AST generator written in Python
```
```
$ pacman -Qs gitless
local/gitless-git 0.8.6.r46.g99b06ba-1
    A scientifically proven easier-to-use git interface
```

Best regards

**Comment by sirlucjan** [comment]
Sorry, probably problem exists in pygit2. 

https://github.com/libgit2/pygit2/issues/846
