### ISSUE TITLE
gitless crashes on commit

### ISSUE THREAD

**Issue by geppettodivacin** [sdg-mit/gitless#246]
I tried to commit (both with editor and without) and was unable to do so. I got this error:
```
user@OSHCCND051501C:/mnt/c/Users/My.User/Documents/work/ClinicalHistoryService$ gl commit -m 'Factor out consumer config'
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:

  0.8.8

  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/gitless/cli/gl.py", line 99, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "/usr/lib/python3/dist-packages/gitless/cli/gl_commit.py", line 67, in main
      ci = curr_b.create_commit(commit_files, msg, partials=partials)
    File "/usr/lib/python3/dist-packages/gitless/core.py", line 1250, in create_commit
      msg, get_tree_and_update_index(),  # the commit tree
    File "/usr/lib/python3/dist-packages/gitless/core.py", line 1222, in get_tree_and_update_index
      update()
    File "/usr/lib/python3/dist-packages/gitless/core.py", line 1215, in update
      index.remove(git_f)
    File "/usr/lib/python3/dist-packages/pygit2/index.py", line 173, in remove
      check_error(err, True)
    File "/usr/lib/python3/dist-packages/pygit2/errors.py", line 50, in check_error
      raise IOError(message)
  OSError: index does not contain ClinicalHistoryService/Modules/BasePipelineConfiguration.cs at stage 0
```

Here's the current `gl status`:
```
user@OSHCCND051501C:/mnt/c/Users/Eric.Dilmore/Documents/work/ClinicalHistoryService$ gl status
On branch dev/11154/ClinicalBinCDC, repo-directory //

Tracked files with modifications:
  ➜ these will be automatically considered for commit
  ➜ use gl untrack f if you don't want to track changes to file f
  ➜ if file f was committed before, use gl checkout f to discard local changes

    ClinicalHistoryService/Configuration/EventSectionConfig.cs
    ClinicalHistoryService/Modules/BasePipelineConfiguration.cs (deleted)
    ClinicalHistoryService/Modules/ClinicalBin/ClinicalBinEventHandler.cs
    ClinicalHistoryService/Modules/ClinicalBin/Config/ClinicalBinEventHandlerConfiguration.cs
    ClinicalHistoryService/Modules/ClinicalBin/Config/ClinicalBinEventPipelineConfiguration.cs
    ClinicalHistoryService/Modules/IConsumerConfig.cs (new file)
    ClinicalHistoryService/Modules/OshStatefulEventHandler.cs
    ClinicalHistoryService/Modules/PatientLabs/Config/PatientLabsEventPipelineConfiguration.cs


Untracked files:
  ➜ these won't be considered for commit
  ➜ use gl track f if you want to track changes to file f

    There are no untracked files to list
```

**Comment by geppettodivacin** [comment]
This seems to be a duplicate of #162 , sorry.
