### ISSUE TITLE
Exception on commit: Unexpected output of ls-files

### ISSUE THREAD

**Issue by apblack** [sdg-mit/gitless#32]
I get this when trying to commit with <code>gl commit  -exc known-good -m ...</code>
<pre>
# Oops...something went wrong (recall that Gitless is in beta). If you want to help, re
port the bug at http://gitless.com/community.html and include the following in the emai
l:

GL Version: 0.5

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gitless/cli/gl.py", line 69, in main
    return SUCCESS if args.func(args) else ERRORS_FOUND
  File "/usr/local/lib/python2.7/site-packages/gitless/cli/gl_commit.py", line 48, in main
    if not _valid_input(only_files, exc_files, inc_files):
  File "/usr/local/lib/python2.7/site-packages/gitless/cli/gl_commit.py", line 145, in _valid_input
    f = file_lib.status(fp)
  File "/usr/local/lib/python2.7/site-packages/gitless/core/file.py", line 211, in status
    return _status(fp)[0]
  File "/usr/local/lib/python2.7/site-packages/gitless/core/file.py", line 286, in _status
    git_s = git_status.of_file(fp)
  File "/usr/local/lib/python2.7/site-packages/gitpylib/status.py", line 55, in of_file
    return _status_from_output(s, _is_au_file(fp), fp)
  File "/usr/local/lib/python2.7/site-packages/gitpylib/status.py", line 129, in _is_au_file
    raise Exception('Unexpected output of ls-files: {0}'.format(out))
Exception: Unexpected output of ls-files: H known-good/.gitignore
H known-good/Makefile
H known-good/independent/c-4df500fa93a8e8f5886b3590424a7aa67e21bf0e.tar.gz
H known-good/make-known-good
</pre>

Note that the "unexpected output" is comming from the directory that I'm trying to exclude from the commit.

**Comment by spderosso** [comment]
343e7ac94a42377d97cef08d7693bb381aa758f0

**Comment by spderosso** [comment]
Fix will go out in next release (0.7)
