### ISSUE TITLE
rebase --abort failed

### ISSUE THREAD

**Issue by rodrigob** [sdg-mit/gitless#34]
```
# Oops...something went wrong (recall that Gitless is in beta). If you want to help, report the bug at http://gitless.com/community.html and include the following information:

0.6.2

Traceback (most recent call last):
  File "/home/benenson/.local/lib/python3.2/site-packages/gitless/cli/gl.py", line 73, in main
    return SUCCESS if args.func(args) else ERRORS_FOUND
  File "/home/benenson/.local/lib/python3.2/site-packages/gitless/cli/gl_rebase.py", line 35, in main
    if sync_lib.abort_rebase() is sync_lib.REBASE_NOT_IN_PROGRESS:
  File "/home/benenson/.local/lib/python3.2/site-packages/gitless/core/sync.py", line 121, in abort_rebase
    git_sync.abort_rebase()
  File "/home/benenson/.local/lib/python3.2/site-packages/gitpylib/sync.py", line 118, in abort_rebase
    common.safe_git_call('rebase --abort')
  File "/home/benenson/.local/lib/python3.2/site-packages/gitpylib/common.py", line 40, in safe_git_call
    raise Exception('%s failed: out is %s, err is %s' % (cmd, out, err))
Exception: rebase --abort failed: out is , err is No rebase in progress?
```

**Comment by spderosso** [comment]
Since v0.8 (https://github.com/sdg-mit/gitless/releases/tag/v0.8) we have no `rebase` command so I am closing this issue. Let me know if you ran into a similar bug with `fuse`
