### ISSUE TITLE
gl status error

### ISSUE THREAD

**Issue by Tinche** [sdg-mit/gitless#38]
# On branch worker-background, repo-directory //
# Oops...something went wrong (recall that Gitless is in beta). If you want to help, report the bug at http://gitless.com/community.html and include the following information:

0.6.2

Traceback (most recent call last):
  File "/Users/ttvrtkovic/.local/venvs/gitless/lib/python2.7/site-packages/gitless/cli/gl.py", line 73, in main
    return SUCCESS if args.func(args) else ERRORS_FOUND
  File "/Users/ttvrtkovic/.local/venvs/gitless/lib/python2.7/site-packages/gitless/cli/gl_status.py", line 45, in main
    for f in file_lib.status_all(include_tracked_unmodified_fps=False):
  File "/Users/ttvrtkovic/.local/venvs/gitless/lib/python2.7/site-packages/gitless/core/file.py", line 227, in status_all
    include_tracked_unmodified_fps=include_tracked_unmodified_fps):
  File "/Users/ttvrtkovic/.local/venvs/gitless/lib/python2.7/site-packages/gitpylib/status.py", line 86, in of_repo
    status = _status_from_output(s, s_fp in au_fps, s_fp)
  File "/Users/ttvrtkovic/.local/venvs/gitless/lib/python2.7/site-packages/gitpylib/status.py", line 187, in _status_from_output
    raise Exception('Failed to get status of file {0}, s is "{1}"'.format(fp, s))
Exception: Failed to get status of file ngs_worker/workers/social.py, s is "D "

social.py has been marked as deleted.

**Comment by spderosso** [comment]
Thanks Tin for reporting this, I'll look into it. It might have been fixed with the v0.7 release since I made quite a few improvements to status.

**Comment by spderosso** [comment]
This is probably fixed by now. You can try updating to the current release.
