### ISSUE TITLE
Crash when trying to commit

### ISSUE THREAD

**Issue by toomim** [sdg-mit/gitless#49]
```
$ gl commit 
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.3
  
  Traceback (most recent call last):
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl", line 69, in main
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl_commit", line 51, in main
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.commit_dialog", line 61, in show
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.commit_dialog", line 71, in _launch_editor
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/subprocess", line 522, in call
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/subprocess", line 710, in __init__
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/subprocess", line 1335, in _execute_child
  OSError: [Errno 2] No such file or directory
```

**Comment by spderosso** [comment]
6bc86d698c20b0b3fcd2ef1be1ff4e632c167be6
