### ISSUE TITLE
commit fails after file rename

### ISSUE THREAD

**Issue by colemanbroad** [sdg-mit/gitless#63]
colemanbroaddus@myers-mac-10-display-1 ~/P/cell_tracker> gl status
On branch master, repo-directory //

Tracked files with modifications:
  ➜ these will be automatically considered for commit
  ➜ use gl untrack f if you don't want to track changes to file f
  ➜ if file f was committed before, use gl checkout f to discard local changes

    master.py
    truetree.py (new file)
    viewer.py (deleted)

Untracked files:
  ➜ these won't be considered for commit
  ➜ use gl track f if you want to track changes to file f

    There are no untracked files to list
colemanbroaddus@myers-mac-10-display-1 ~/P/cell_tracker> gl commit -m "Merged changes from nodeless."
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.3
  
  Traceback (most recent call last):
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl", line 69, in main
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl_commit", line 58, in main
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.core", line 1179, in create_commit
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.core", line 1152, in get_tree_and_update_index
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.core", line 1145, in update
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/pygit2.index", line 168, in remove
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/pygit2.errors", line 53, in check_error
  IOError: Index does not contain viewer.py at stage 0

**Comment by colemanbroad** [comment]
This happened directly after a **merge** and **resolve**, although they did *not* include the file causing the error: (`viewer.py` renamed to `truetree.py`).
